(function() {var implementors = {
"forest_auth":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_auth/enum.Error.html\" title=\"enum forest_auth::Error\">Error</a>"]],
"forest_blocks":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_blocks/enum.Error.html\" title=\"enum forest_blocks::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_blocks/header/enum.BlockHeaderBuilderError.html\" title=\"enum forest_blocks::header::BlockHeaderBuilderError\">BlockHeaderBuilderError</a>"]],
"forest_chain":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_chain/enum.Error.html\" title=\"enum forest_chain::Error\">Error</a>"]],
"forest_db":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_db/enum.Error.html\" title=\"enum forest_db::Error\">Error</a>"]],
"forest_deleg_cns":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_deleg_cns/enum.DelegatedConsensusError.html\" title=\"enum forest_deleg_cns::DelegatedConsensusError\">DelegatedConsensusError</a>"]],
"forest_encoding":[],
"forest_fil_cns":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_fil_cns/enum.FilecoinConsensusError.html\" title=\"enum forest_fil_cns::FilecoinConsensusError\">FilecoinConsensusError</a>"]],
"forest_ipld":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_ipld/enum.Error.html\" title=\"enum forest_ipld::Error\">Error</a>"]],
"forest_key_management":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_key_management/enum.Error.html\" title=\"enum forest_key_management::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_key_management/enum.EncryptedKeyStoreError.html\" title=\"enum forest_key_management::EncryptedKeyStoreError\">EncryptedKeyStoreError</a>"]],
"forest_legacy_ipld_amt":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_legacy_ipld_amt/enum.Error.html\" title=\"enum forest_legacy_ipld_amt::Error\">Error</a>"]],
"forest_message_pool":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_message_pool/enum.Error.html\" title=\"enum forest_message_pool::Error\">Error</a>"]],
"forest_state_manager":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_state_manager/enum.Error.html\" title=\"enum forest_state_manager::Error\">Error</a>"]],
"forest_state_migration":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forest_state_migration/enum.MigrationError.html\" title=\"enum forest_state_migration::MigrationError\">MigrationError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()